### ISSUE TITLE
Speaker coordinations   

### ISSUE THREAD

**Issue by NothingEverHappens** [AngularNYC/meetup#139]
# Time commitment
before the event: 1 hour

# Speaker1 Role description (Torgeir Helgevold)
ASAP: 
- [x] Ask @kirjs  to connect you to the speaker
- [x] Confirm speakers availability for 2017-06-29
- [x] Get speaker in the chat with all the organizers and brainstorm the exact topic details
- [x] Send them "the speaker message" on slack cc @kirjs (find, the text below)
- [x] Post  Full Name, twitter handler, photo, talk title and talk description here and reference the event host issue (#148)
- [x] Get video release signed and emailed to "release-form-repository@google.com" cc kirjs@google.com
- [x] Send a nice reminder couple of days in advance

# Speaker2 Role description
ASAP
- [x] Ask @kirjs  to connect you to the speaker
- [x] Reach out to them, and confirm their availability for 2017-06-29
- [x] Send them the speaker email (below)
- [ ] Post  Full Name, twitter handler, photo, talk title and talk description here and reference the event host issue  (#148)
- [ ] Get video release signed and emailed to "release-form-repository@google.com"  cc kirjs@google.com
- [ ] Send a nice reminder couple of days in advance

# Speaker3 Role description (Uma Moiseenko)
ASAP
- [x] Ask @kirjs  to connect you to the speaker
- [x] Reach out to them, and confirm their availability for 2017-06-29
- [x] Send them the speaker email (below)
- [x] Get video release signed and emailed to "release-form-repository@google.com"  cc kirjs@google.com
- [x] Post  Full Name, twitter handler, photo, talk title and talk description here and reference the event host issue  (#148)
- [x] Send a nice reminder couple of days in advance

# Speaker4 Role description (Kirill Cherkashin @kirjs)
ASAP
- [x] Ask @kirjs  to connect you to the speaker
- [x] Reach out to them, and confirm their availability for 2017-06-29
- [x] Send them the speaker email (below)
- [x] Post  Full Name, twitter handler, photo, talk title and talk description here and reference the event host issue  (#148)
- [x] Get video release signed and emailed to "release-form-repository@google.com"  cc kirjs@google.com
- [x] Send a nice reminder couple of days in advance

# Find a potential speaker and reach out to them 
Check out [Speaker FAQ](https://docs.google.com/document/d/1ZIvF0g1qSmcJK99yK1tnl2LTFmYOi5g2xXodQ9RJDNs/edit#heading=h.h61pupkuj67r)

# Speaker email

Hi %SPEAKER_NAME%
 
Looking forward to your talk at the %DATE% AngularJS NYC meetup!
The location is %OFFICE LOCATION WITH LINK TO GOOGLE MAPS%
 
You’ll be the second|first speaker, %TIME_SLOT_CONFIRM_WITH_KIRJS% please let me know if you feel strongly about going first|second). 
 
Speaker's checklist:
[ASAP] Send me the talk title, description and your photo/information (example)
[Before the meetup] Sign the speaker release form (attached) and send it back to me.
[Before the meetup] Add your information to the slide deck (%GET A LINK FROM SLIDE DECK PERSON%) 
[Before the meetup] If your guests get stuck in the waitlist - let me know!
[%DATE%] Come 15 minutes in advance (5:45) to go through the setup process.
 
Additional information:
The talks are usually 20-30 minutes.
Our projector resolution is 720p
We’re expecting to have 200 people at the meetup.
We also have a [Speaker's FAQ](https://docs.google.com/document/d/1ZIvF0g1qSmcJK99yK1tnl2LTFmYOi5g2xXodQ9RJDNs/edit#heading=h.h61pupkuj67r) with more information
 
Feel free to reach out to me if you have any questions.
 
Thanks,
Kirill

# FAQ

**Comment by kirjs** [comment]
And the first speaker is Torgeir Helgevold `torgeir-nyc` on slack

**Comment by RingoKam** [comment]
Send Tor slack message.

**Comment by tessaSAC** [comment]
*Sent? @RingoKam

**Comment by Nehal90** [comment]
@RingoKam Hi Ringo, when you get the "talk title, description and photo" from the speaker, please forward it to an425@live.com. Thank you :)

**Comment by kirjs** [comment]
Can I suggest posting it here?

**Comment by Nehal90** [comment]
Yea of course. I wasn't sure if images can be posted here :(

**Comment by kirjs** [comment]
Yes, just drag and drop works!

**Comment by kirjs** [comment]
[Video_Google_speaker_release (2).pdf](https://github.com/AngularNYC/meetup/files/1059785/Video_Google_speaker_release.2.pdf)

**Comment by RingoKam** [comment]
@Nehal90 
Title: "Angular in production"
Name: "Torgeir Helgevold"
Description: "I will talk about different approaches that can be used to optimize Angular production builds. I will show examples.demo and discuss the pros and cons of each method."
Twitter: @helgevold
Photo:
![tor-bio-pic](https://user-images.githubusercontent.com/10913199/26909946-0cefc5d2-4bd2-11e7-914b-54017d0a5696.jpg)

**Comment by RingoKam** [comment]
@barlanj Be sure to use the new form @kirjs posted 

> Video_Google_speaker_release (2).pdf

**Comment by kirjs** [comment]
Got all speaker issues together, because otherwise I had to make every change in 2 places

**Comment by kirjs** [comment]
Test #148

**Comment by barlanj** [comment]
@RingoKam Added Uma to the speakers list. I'll go ahead and confirm, but going to CC you in email.

**Comment by Nehal90** [comment]
@RingoKam @barlanj Hi guys, do you have details of the second talk? If you do, please post it here so we can put it up on meetup. Thanks :)

**Comment by barlanj** [comment]
Second speaker is supposed to be vadim and his brother, but I've not received the talk or description - didn't want to confirm until I have those. Supposed to get it this week. I'll reping to remind him.

**Comment by Nehal90** [comment]
Thank you Joseph @barlanj

**Comment by barlanj** [comment]
@Nehal90
Title: RxJs 101
Name: Uma Moiseenko
Twitter: 
Description: In this talk, I'll cover the basics behind RxJs Observables and Promises. What's the difference between the two? Why would you choose one over the other? We'll look at code samples to figure out the answers to these questions. My goal is to ensure that everyone who has never worked with Observables will leave with a basic understanding of the concept!
![image](https://user-images.githubusercontent.com/10227672/27505137-79c80f48-5866-11e7-974d-8eb64faa07b8.png)

**Comment by Nehal90** [comment]
Thanks @barlanj . Meetup title and details have been updated. Fyi @kirjs

**Comment by barlanj** [comment]
@Nehal90
Title: Lazy content components.
Name: Kirill Cherkashin
Twitter: @kirjs
Description: In semi-live-coding-session we'll dig into how to prevent angular from instantiating components which are in the template, but are not yet displayed. 

![image](https://user-images.githubusercontent.com/10227672/27666696-a42509fe-5c43-11e7-9e28-3b7987583b68.png)

**Comment by Nehal90** [comment]
Which meetup event this speaker is presenting at? Tomorrow's? 😮 
If tomorrow, then which time slot?
@barlanj @kirjs

**Comment by barlanj** [comment]
@Nehal90 Yup. kirill is presenting tomorrow. No idea who has what time slots though. @kirjs ?

**Comment by kirjs** [comment]
I'll go last2:20 PM, June 28, 2017, "Joseph B." <notifications@github.com>:@Nehal90 Yup. kirill is presenting tomorrow. No idea who has what time slots though. @kirjs ?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




Sent from Yandex.Mail for mobile: http://m.ya.ru/ymail

**Comment by Nehal90** [comment]
ok cool. I'll update the event

**Comment by RingoKam** [comment]
all done guys! gj
