### ISSUE TITLE
[Oneof] Measure the podium on stage

### ISSUE THREAD

**Issue by ilyagelman** [AngularNYC/meetup#156]
There is a dull black podium on the stage that we want to decorate with a beautiful Angular sign. For that we need to know what the dimensions of the podium are.

# Subtasks
- [x] Measure the top part of the podium
- [x] Measure the bottom part of the podium
- [x] Double check measurements, because we are going to print a banner exactly with these dimensions

**Comment by bruno78** [comment]
When do you guys need to have it measured?

**Comment by kirjs** [comment]
Either one of the Friday meetings (there's a chance that the room would be occupied), or before the event on 6/26

**Comment by bruno78** [comment]
![elev podium](https://user-images.githubusercontent.com/10203714/26905775-419ae55c-4bb7-11e7-9620-d49ae16084f5.jpeg)

**Comment by ilyagelman** [comment]
Wow!
