### ISSUE TITLE
Speaker Coordinations

### ISSUE THREAD

**Issue by bruno78** [AngularNYC/meetup#170]
# Time commitment
before the event: 1 hour

# Speaker 1 (Eudes) Role description
ASAP: 
- [x] Ask @kirjs  to connect you to the speaker
- [x] Confirm speaker's availability for 2017-07-25
- [x] Get speaker in the chat with all the organizers and brainstorm the exact topic details
- [x] Send them "the speaker message" on slack cc @kirjs (find, the text below)
- [x] Post  Full Name, twitter handler, photo, talk title and talk description here and reference the event host issue (#148)
- [x] Get [video release](https://github.com/nycJSorg/meetups/files/1148914/Video_Google_speaker_release.2.1.pdf) signed and emailed to "release-form-repository@google.com" cc kirjs@google.com
- [x] Send a nice reminder couple of days in advance

# Speaker 2 (Jo) Role description
ASAP
- [x] Ask @kirjs  to connect you to the speaker
- [x] Confirm speaker's availability for 2017-07-25
- [x] Get speaker in the chat with all the organizers and brainstorm the exact topic details
- [ ] Send them "the speaker message" on slack cc @kirjs (find, the text below)
- [x] Post  Full Name, twitter handler, photo, talk title and talk description here and reference the event host issue (#148)
- [ ] Get [video release](https://github.com/nycJSorg/meetups/files/1148914/Video_Google_speaker_release.2.1.pdf) signed and emailed to "release-form-repository@google.com" cc kirjs@google.com
- [ ] Send a nice reminder couple of days in advance

# Speaker 3 (Sophia) Role description
ASAP
- [x] Ask @kirjs  to connect you to the speaker
- [x] Confirm speaker's availability for 2017-07-25
- [x] Get speaker in the chat with all the organizers and brainstorm the exact topic details
- [x] Send them "the speaker message" on slack cc @kirjs (find, the text below)
- [x] Post  Full Name, twitter handler, photo, talk title and talk description here and reference the event host issue (#148)
- [x] Get [video release](https://github.com/nycJSorg/meetups/files/1148914/Video_Google_speaker_release.2.1.pdf) signed and emailed to "release-form-repository@google.com" cc kirjs@google.com
- [x] Send a nice reminder couple of days in advance

# Speaker 4 Role description
ASAP
- [ ] Ask @kirjs  to connect you to the speaker
- [ ] Confirm speaker's availability for 2017-07-25
- [ ] Get speaker in the chat with all the organizers and brainstorm the exact topic details
- [ ] Send them "the speaker message" on slack cc @kirjs (find, the text below)
- [ ] Post  Full Name, twitter handler, photo, talk title and talk description here and reference the event host issue (#148)
- [ ] Get [video release](https://github.com/nycJSorg/meetups/files/1148914/Video_Google_speaker_release.2.1.pdf) signed and emailed to "release-form-repository@google.com" cc kirjs@google.com
- [ ] Send a nice reminder couple of days in advance

# Find a potential speaker and reach out to them 
Check out [Speaker FAQ](https://docs.google.com/document/d/1ZIvF0g1qSmcJK99yK1tnl2LTFmYOi5g2xXodQ9RJDNs/edit#heading=h.h61pupkuj67r)

# Speaker email

Hi %SPEAKER_NAME%
 
Looking forward to your talk at the %DATE% AngularJS NYC meetup!
The location is %OFFICE LOCATION WITH LINK TO GOOGLE MAPS%
 
You’ll be the second|first speaker, %TIME_SLOT_CONFIRM_WITH_KIRJS% please let me know if you feel strongly about going first|second). 
 
Speaker's checklist:
[ASAP] Send me the talk title, description and your photo/information (example)
[Before the meetup] Sign the speaker release form (attached) and send it back to me.
[Before the meetup] Add your information to the slide deck (%GET A LINK FROM SLIDE DECK PERSON%) 
[Before the meetup] If your guests get stuck in the waitlist - let me know!
[%DATE%] Come 15 minutes in advance (5:45) to go through the setup process.
 
Additional information:
The talks are usually 20-30 minutes.
Our projector resolution is 720p
We’re expecting to have 200 people at the meetup.
We also have a [Speaker's FAQ](https://docs.google.com/document/d/1ZIvF0g1qSmcJK99yK1tnl2LTFmYOi5g2xXodQ9RJDNs/edit#heading=h.h61pupkuj67r) with more information
 
Feel free to reach out to me if you have any questions.
 
Thanks,
Kirill

**Comment by tessaSAC** [comment]
Where is the video release @kirjs @irsick?

**Comment by kirjs** [comment]
[Video_Google_speaker_release.2 (1).pdf](https://github.com/nycJSorg/meetups/files/1148914/Video_Google_speaker_release.2.1.pdf)

**Comment by tessaSAC** [comment]
Since you two need most of this info for your tasks I'm assigning you this one lol

**Comment by Nehal90** [comment]
Waiting on Jo's pretty picture :)

**Comment by tessaSAC** [comment]
Just sent it to you :)

**Comment by tessaSAC** [comment]
How's the progress on this task looking?

**Comment by tessaSAC** [comment]
Did either of you send the speaker messages and get video releases signed?
